#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-asn1crypto
Version  : 0.24.0
Release  : 28
URL      : http://pypi.debian.net/asn1crypto/asn1crypto-0.24.0.tar.gz
Source0  : http://pypi.debian.net/asn1crypto/asn1crypto-0.24.0.tar.gz
Summary  : Fast ASN.1 parser and serializer with definitions for private keys, public keys, certificates, CRL, OCSP, CMS, PKCS#3, PKCS#7, PKCS#8, PKCS#12, PKCS#5, X.509 and TSP
Group    : Development/Tools
License  : MIT
Requires: deprecated-asn1crypto-license = %{version}-%{release}
Requires: deprecated-asn1crypto-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : python-core
BuildRequires : setuptools-legacypython

%description
# asn1crypto
A fast, pure Python library for parsing and serializing ASN.1 structures.

%package legacypython
Summary: legacypython components for the deprecated-asn1crypto package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-asn1crypto package.


%package license
Summary: license components for the deprecated-asn1crypto package.
Group: Default

%description license
license components for the deprecated-asn1crypto package.


%package python
Summary: python components for the deprecated-asn1crypto package.
Group: Default

%description python
python components for the deprecated-asn1crypto package.


%prep
%setup -q -n asn1crypto-0.24.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554307711
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-asn1crypto
cp LICENSE %{buildroot}/usr/share/package-licenses/deprecated-asn1crypto/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-asn1crypto/LICENSE

%files python
%defattr(-,root,root,-)
